config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", omniauth_callbacks: "omniauth_callbacks"}, :path => 'accounts'

  resources :projects do
    resources :team_members
    patch 'team_members', to: 'team_members#update_multiple', as: 'update_team_members'
    resources :tasks
    post 'tasks/:id/toggle_complete', to: 'tasks#toggle_complete', as: 'toggle_task_complete'
  end

  root to: 'static#index'
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  enum :role => [:view, :edit]

  def self.create_multiple(team_members_attrs)
    begin
      TeamMember.transaction do
        team_members_attrs.each do |k,attrs|
          unless attrs[:role] == 'none'
            team_member = self.create!(user_id: attrs[:user_id], project_id: attrs[:project_id])
            team_member.send("#{attrs[:role]}!")
          end
        end
      end
      true
    rescue
      false
    end
  end

  def self.update_multiple(team_members_attrs)
    begin
      TeamMember.transaction do
        team_members_attrs.each do |team_member_id, attrs|
          if attrs[:role] == 'none'
            TeamMember.find_by(id: team_member_id).destroy
          else
            team_member = TeamMember.find_by(id: team_member_id)
            team_member.send("#{attrs[:role]}!")
          end
        end
      end
      true
    rescue
      false
    end
  end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_project, only: [:index, :new, :create, :update_multiple]

  def index
    @team_members = @project.team_members.includes(:user)
    authorize @project, :view_team_members?
  end

  def new
    @users = User.not_on_team(@project).reject do |user|
      @project.owner == user
    end
    authorize @project, :add_team_members?
  end

  def create
    authorize @project, :add_team_members?
    if TeamMember.create_multiple(team_members_params[:users])
      redirect_to project_team_members_path(@project), notice: 'Permissions updated!'
    else
      flash[:alert] = "There was an issue updating user permissions. Try again."
      @users = User.not_on_team(@project).reject do |user|
        @project.owner == user
      end
      render :new
    end
  end

  def update_multiple
    authorize @project, :edit_permissions?
    if TeamMember.update_multiple(team_members_params[:users])
      redirect_to project_team_members_path(@project), notice: 'Permissions updated!'
    else
      binding.pry
      flash[:alert] = "There was an issue updating user permissions. Try again."
      @team_members = @project.team_members.includes(:user)
      render :index
    end
  end

  private

  def set_project
    @project = Project.find_by(id: params[:project_id])
  end

  def team_members_params
    params.permit(users: [:role, :project_id, :user_id])
  end
end

app/views/team_members/_team_member.html.erb
<tr>
  <td><%= team_member.user.username %></td>
  <td><%= team_member.role.capitalize %></td>
</tr>

app/views/team_members/_update_permissions.html.erb
<%= form_tag project_update_team_members_path(@project), method: :patch do %>
    <table class="table table-hover">
      <tr>
        <th>Username</th>
        <th>Permissions</th>
      </tr>
    <% if @project.owner == current_user %>
      <tr>
        <td>You</td>
        <td>You are the owner of this project!</td>
      </tr>
    <% end %>
    <% @team_members.each do |team_member| %>
      <tr>
        <td><%= team_member.user.username %></td>
        <td>
          <%= hidden_field_tag "users[#{ team_member.id }][project_id]", @project.id %>
          <%= hidden_field_tag "users[#{ team_member.id }][user_id]", team_member.user.id %>
          <%= radio_button_tag "users[#{ team_member.id }][role]", 'none' %> None
          <%= radio_button_tag "users[#{ team_member.id }][role]", 'view', (true if team_member.role == 'view') %> View
          <%= radio_button_tag "users[#{ team_member.id }][role]", 'edit', (true if team_member.role == 'edit') %> Edit
        </td>
      </tr>
    <% end %>
  </table>
  <%= submit_tag 'Update Permissions', class: 'btn btn-primary' %>
<% end %>

app/views/team_members/index.html.erb
<%= content_tag :h1, @project.title %>

<h3>Project Team Members</h3>
<% if current_user.has_role? @project, :edit %>
  <%= render partial: 'update_permissions', locals: { team_members: @team_members } %>
<% else %>
  <table class="table table-hover">
    <tr>
      <th>Username</th>
      <th>Permissions</th>
    </tr>
    <%= render(@team_members) || "No Team members." %>
  </table>
<% end %>

<% if current_user.has_role? @project, :edit %>
  <h4>Admin options:</h4>
  <%= link_to 'Add Team Members', new_project_team_member_path(@project) %> |
<% end %>

<%= link_to 'Back to project', project_path(@project) %>

app/views/team_members/new.html.erb
<h1><%= @project.title %></h1>
<%= link_to 'Back to project', project_path(@project) %>

<h3>Add Team members</h3>
<% if @users.empty? %>
  There are no users to add who aren't already members of the project!
<% else %>
  <%= form_tag project_team_members_path(@project) do %>
    <table class="table table-hover">
      <tr>
        <th>Username</th>
        <th>Permissions</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td>
            <%= hidden_field_tag "users[#{ user.id }][project_id]", @project.id %>
            <%= hidden_field_tag "users[#{ user.id }][user_id]", user.id %>
            <%= radio_button_tag "users[#{ user.id }][role]", 'none', checked: true %> None
            <%= radio_button_tag "users[#{ user.id }][role]", 'view'  %> View
            <%= radio_button_tag "users[#{ user.id }][role]", 'edit' %> Edit
          </td>
        </tr>
      <% end %>
    </table>
    <%= submit_tag 'Update Permissions', class: 'btn btn-primary' %>
  <% end %>
<% end %>