config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", omniauth_callbacks: "omniauth_callbacks"}, :path => 'accounts'

  resources :projects do
    resources :team_members
    patch 'team_members', to: 'team_members#update_multiple', as: 'update_team_members'
    resources :tasks
    post 'tasks/:id/toggle_complete', to: 'tasks#toggle_complete', as: 'toggle_task_complete'
  end

  root to: 'static#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessor :emails_invited, :valid_emails, :invalid_emails

  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :team_members, :dependent => :destroy
  has_many :tasks, :dependent => :destroy

  validates :title,
    :presence => true,
    :length => {
      :in => 6..155
    },
    :uniqueness => { :scope => :owner }
  validates :description,
    :presence => true,
    :length => {
      :in => 20..400
    }
  validates :owner, :presence => true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy, :add_team_members, :edit_permissions, :view_team_members]

  def index
    @projects = policy_scope(Project)
  end

  def new
    @project = current_user.projects.build
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    authorize @project
    if @project.save
      redirect_to project_path(@project), notice: 'Your new project has been created!'
    else
      render :new, alert: 'There was a problem saving your project.'
    end
  end

  def edit
    authorize @project
  end

  def update
    @project = Project.find_by(id: params[:id])
    authorize @project
    if @project.update(project_params)
      redirect_to project_path(@project), notice: 'Your project has been updated.'
    else
      render :edit, alert: 'There was a problem saving your changes.'
    end
  end

  def show
    @team_members = @project.team_members.reject  do |team_member|
      team_member.user == @project.owner
    end
    @tasks = @project.tasks
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: "#{@project.title} was destroyed successfully."
  end

  private

  def set_project
    @project = Project.find_by(id: params[:id])
    authorize @project
  end

  def project_params
    params.require(:project).permit(:title, :description, :user_id, team_members: [:id, :role])
  end
end

app/views/projects/_form.html.erb
<%= bootstrap_form_for project do |f| %>
  <%= f.hidden_field :user_id %>
  <%= f.text_field :title %>
  <%= f.text_area :description %>
  <%= f.primary %>
<% end %>

app/views/projects/_project.html.erb
<li>
  <%= link_to project_path(project) do %>
    <span class="glyphicon glyphicon-list"></span> <%= project.title.capitalize %>
  <% end %>
</li>

app/views/projects/_project_details_admin.html.erb
<li>
  <%= link_to edit_project_path(project) do %>
    <span class="glyphicon glyphicon-pencil"></span>
  <% end %>
</li>
<li>
  <%= link_to project_team_members_path(project) do %>
    <span class="glyphicon glyphicon-user"></span>
  <% end %>
</li>
<li>
  <% if policy(project).destroy?  %>
    <%= link_to project_path(project), method: :delete do %>
      <span class="glyphicon glyphicon-remove"></span>
    <% end %>
  <% end %>
</li>

app/views/projects/_tasks_list.html.erb
<li class="<%= 'completed' if task.completed %>">
  <span class="glyphicon glyphicon-<%= task.completed ? 'check' : 'unchecked' %>"></span>
  <%= task.description %>
</li>

app/views/projects/_tasks_list_admin.html.erb
<li class="<%= 'completed' if task.completed %>">
    <%= link_to project_toggle_task_complete_path(task.project, task), method: :post do %>
      <span class="glyphicon glyphicon-<%= task.completed ? 'check' : 'unchecked' %>"></span>
    <% end %>
  <%= task.description %>
  <div class="task-controls">
    <%= link_to project_task_path(task.project, task), method: :delete do %>
      <span class="glyphicon glyphicon-remove-circle"></span>
    <% end %>
  </div>
</li>

app/views/projects/_team_members.html.erb
<tr>
  <td><%= team_member.user.username %></td>
  <td><%= team_member.role.capitalize %></td>
</tr>

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Update Project</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
    <p class="notes">You can update your project information at any time.</p>
  </div>
  <div class="col-md-9">
    <%= render partial: 'form', locals: { project: @project } %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-12">
    <ul class="projects-list">
      <%= render @projects %>
      <li>
        <%= link_to new_project_path do %>
          <span class="glyphicon glyphicon-plus-sign"></span>New Project
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Start A Project</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
    <p class="notes">Make a new project and invite current users to join the project's team and collaborate.</p>
  </div>
  <div class="col-md-9">
    <%= render partial: 'form', locals: { project: @project } %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-10">
    <h3 class="project-titles"><%= @project.title %></h3>
  </div>
</div>

<div class="row">
  <div class="col-sm-2 border-right">
    <ul class="project-details">
      <% if current_user.has_role? @project, :edit %>
        <%= render partial: 'project_details_admin', locals: { project: @project, team_members: @team_members } %>
      <% else %>
        <li>
          <%= link_to project_team_members_path(@project) do %>
            <span class="glyphicon glyphicon-user"></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-10">
    <ul class="tasks-list">
      <% if current_user.has_role? @project, :edit %>
        <%= render partial: 'tasks_list_admin', collection: @project.tasks, as: :task %>
      <% else %>
        <%= render partial: 'tasks_list', collection: @project.tasks, as: :task %>
      <% end %>
      <li>
        <%= link_to new_project_task_path(@project) do %>
          <span class="glyphicon glyphicon-plus-sign"></span> Add Task
        <% end %>
      </li>
    </ul>
  </div>
</div>