config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", omniauth_callbacks: "omniauth_callbacks"}, :path => 'accounts'

  resources :projects do
    resources :team_members
    patch 'team_members', to: 'team_members#update_multiple', as: 'update_team_members'
    resources :tasks
    post 'tasks/:id/toggle_complete', to: 'tasks#toggle_complete', as: 'toggle_task_complete'
  end

  root to: 'static#index'
end

app/views/layouts/_logged_in_nav.html.erb
<ul class="nav navbar-nav">
  <li>
    <%= link_to projects_path do %>
      <span class="nav-icon glyphicon glyphicon-th-list"></span><span class="sub-title">My Projects</span></a>
    <% end %>
  </li>
  <li>
    <%= link_to new_project_path do %>
      <span class="nav-icon glyphicon glyphicon-plus-sign"></span><span class="sub-title">New Project</span></a>
    <% end %>
  </li>
</ul>
<ul class="nav navbar-nav navbar-right">
  <li>
    <%= link_to edit_user_registration_path do %>
      <span class="nav-icon glyphicon glyphicon-user"></span><span class="sub-title">My Account</span></a>
    <% end %>
  </li>
  <li>
    <%= link_to destroy_user_session_path, method: :delete do %>
      <span class="nav-icon glyphicon glyphicon-log-out"></span><span class="sub-title">Sign out</span></a>
    <% end %>
  </li>
</ul>

app/views/layouts/_logged_out_nav.html.erb
<ul class="nav navbar-nav">
</ul>
<ul class="nav navbar-nav navbar-right">
  <li>
    <%= link_to new_user_registration_path do %>
      <span class="nav-icon glyphicon glyphicon-edit"></span><span class="sub-title">Sign up</span></a>
    <% end %>
  </li>
  <li>
    <%= link_to new_user_session_path do %>
      <span class="nav-icon glyphicon glyphicon-log-in"></span><span class="sub-title">Sign in</span></a>
    <% end %>
  </li>
</ul>

app/views/layouts/_notifications.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GenericTaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Static navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-ok"></span></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <% if user_signed_in? %>
        <%= render 'layouts/logged_in_nav' %>
      <% else %>
        <%= render 'layouts/logged_out_nav' %>
      <% end %>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</nav>

<div class="container">
  <%= render 'layouts/notifications' %>
  <%= yield %>
</div> <!-- /container -->


</body>
</html>